### PR TITLE
Add characters exclusion from random string

### PR DESCRIPTION
**Pull request by anuragajwani**

### CODE REVIEW

**Comment by Dschee** [comment]
Hi @anuragajwani and thank you for your pull request.

To be honest, I'm not a fan of adding exclusion parameters to the random `String` initializer. Can you please explain what your use case is and why the case `allCharactersIn` doesn't fulfill your needs?

If you really need exclusion behavior, I would rather have a new `allowedCharactersType` where you can specify a [`CharacterSet`](https://developer.apple.com/documentation/foundation/characterset) object. `CharacterSet` already has a rich API where you can invert, add and also **subtract** other `CharacterSet` objects from. Maybe we can call it `allInCharacterSet(CharacterSet)`?

**Comment by anuragajwani** [comment]
Hi @Dschee ,

I was looking to exclude certain characters (o,O and 0) from the alphanumeric character set. I found more convenient than stating all of the characters excluding those.

On the other hand we could make the CharacterSet return the String containing all of the characters and then passing that String as the payload in as allInCharacterSet. Currently the string containing all characters is within the random initialiser.

```
let allowedCharsString: String = {
            switch allowedCharactersType {
            case .numeric:
                return "0123456789"

            case .alphabetic:
                return "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

            case .alphaNumeric:
                return "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

            case .allCharactersIn(let allowedCharactersString):
                return allowedCharactersString
            }
        }()
```

Anurag

**Comment by Dschee** [comment]
Sorry I don't quite understand what you mean as you wrote it. Your text only makes sense to me, when I assume you meant `allCharactersIn` (which already exists) and not `allInCharacterSet` (which I suggested as a new enum case). And if I understand it correctly, you want to add something like `toString()` to `CharacterSet`?

Well, you're right, that would work, too. I've even found [this SO answer](https://stackoverflow.com/questions/15741631/nsarray-from-nscharacterset/15742659#15742659) which includes a solution to doing this (maybe we should make the code more readable though). Feel free to post a PR including tests and docs, and I'll happily review and merge. Thanks in advance! 👍

**Comment by Dschee** [comment]
Closing due to inactivity.

**Pull request closed without merging**
